feat(Retroblur): add Retroblur theme
spicetify/spicetify-themes pull request #582
Opened 2021-10-21 16:48 UTC by Motschen

Retroblur is a spicetify theme that implements the retrowave/vaporwave aesthetic along with blur effects, a background and so much more:
- Retro-style color scheme
- Background picture
- Blur behind many objects
- Glow around highlighted hyperlinks
- Adapted Lyrics-Plus to show the previous and 3rd next line
- Fix some bugs in Lyrics-Plus
- Made the no lyrics found emoji bounce around the screen like the DVD screensaver
- Many small details and tweaks

Since it's based on the Ziro theme, following features also apply:
- long progress bar
- overhauled artist page
- rounded corners everywhere

2021-11-26 00:36 UTC, RaddedMC commented
I like this! It'd be cool if the background could change image / colour based on the album art of the current song

2021-11-27 14:33 UTC, morpheusthewhite requested changes

2021-11-27 14:33 UTC, morpheusthewhite commented on Retroblur/color.ini
> +; COLOR EXPLANATION
There are several color schemes. You should provide a screenshot for each of them and structure the README as specified in the [contribution guidelines](https://github.com/morpheusthewhite/spicetify-themes/blob/master/CONTRIBUTING.md)

2021-11-27 14:34 UTC, morpheusthewhite commented
Sorry for reviewing this late, I've been quite busy in the last month

2022-03-10 11:26 UTC, afonsojramos commented
@Motschen do you think it still makes sense to merge your PR?

2022-07-05 16:23 UTC, kyrie25 commented
@Motschen I've noticed that the theme is currently still being maintained at your repository. Was wondering if you still wish to move it here or continue the development there?

2022-07-05 19:43 UTC, Motschen commented
Yeah, I'm going to update this PR when I have some more time.

2022-07-06 01:01 UTC, afonsojramos commented
@Motschen worry not, after #766 it will be easier to do it, and you'll be able to keep developing under your repo! I'll close this PR as adding to the repo this way is no longer the objective ✌️

2022-07-06 01:01 UTC, closed without merging