feat: add auto-assign to themes issues and PRs
spicetify/spicetify-themes pull request #700
Opened 2022-03-24 13:42 UTC by afonsojramos

@williamckha initially I had Fluent here, but I'll remove it in another PR.

There are a lot of themes that I do not know the owners yet however. If anyone could help here that would be awesome!

2022-03-24 13:52 UTC, morpheusthewhite requested changes

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/pjaspinski

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/Blacksuan19

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/CharlieS1103

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/CharlieS1103

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/okarin001

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/harbassan

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/grasonchan

2022-03-24 13:52 UTC, morpheusthewhite commented on .github/workflows/auto-assign.yml
> +                "assignees": ["username"]
https://github.com/schnensch0

2022-03-24 14:10 UTC, afonsojramos commented
Thank you @morpheusthewhite! I'll also add all of those as contributors to this repo!

2022-03-24 14:17 UTC, afonsojramos commented
Okay, it seems that it is working for everyone that is already part of the repo!

2022-03-24 14:22 UTC, afonsojramos commented
Please accept the invites to join the Spicetify org and themes repository as soon as you can! 
@pjaspinski @Blacksuan19 @okarin001 @harbassan @grasonchan @schnensch0

2022-03-27 06:56 UTC, morpheusthewhite approved these changes

2022-03-27 10:29 UTC, merged