fix(Bloom): Alignment fixes
spicetify/spicetify-themes pull request #758
Opened 2022-05-12 07:10 UTC by nimsandu

fix- Alignments fixed on sidebar
fix- scroll issues
readme updated by adding a special note and a thanks

2022-05-12 08:01 UTC, afonsojramos requested changes

2022-05-12 08:01 UTC, afonsojramos commented on Bloom/user.css
> +.n87ifzfQlmGX8vkeYGDL {
This class probably needs mapping in [spicetify-cli](https://github.com/spicetify/spicetify-cli), can you check there what it might be?

2022-05-12 08:01 UTC, afonsojramos commented on Bloom/user.css
> +.Y8edH1Yjo4xrW_58czQj {
Same for here.

2022-05-12 08:44 UTC, afonsojramos commented
Also, please try to be more descriptive when answering in GitHub issues other than "sorry sir ill try fix that" 😅

2022-05-15 11:04 UTC, nimsandu commented
@afonsojramos sorry sir ill try fix that 🤣

2022-05-15 11:04 UTC, closed without merging