feat(Ziro): add rose pine color scheme
spicetify/spicetify-themes pull request #881
Opened 2023-01-09 12:41 UTC by EuCaue

Added the rose-piné dark ([default variant](https://rosepinetheme.com/palette#:~:text=Ingredients-,Ros%C3%A9%20Pine,-Base)) color scheme.
Added screenshots as needed.
I had some trouble formatting the Markdown, is correct in this way?

2023-01-18 00:26 UTC, harbassan requested changes

2023-01-18 00:26 UTC, harbassan commented on THEMES.md
> +| ![Playlists](Ziro/screenshots/rose-pine-moon.jpg) | ![Playlists](Ziro/screenshots/rose-pine-moon.jpg) |
```suggestion
| ![Playlists](Ziro/screenshots/rose-pine-moon.jpg) | ![Playlists](Ziro/screenshots/rose-pine-dawn.jpg) |
```

2023-01-22 21:30 UTC, harbassan approved these changes

2023-01-22 21:31 UTC, merged

2023-11-14 14:36 UTC, matteaaaaa commented
pink